guard :rspec, cmd: "bundle exec rspec" do
  watch(%r{^spec/(.+)\.rb$})  { "spec" }
  watch(%r{^lib/(.+)\.e?rb$}) { "spec" }
end

guard :shell do
  watch(%r{^(lib|spec)/(.+)\.rb$})  { `mutest --include lib --use rspec 'GildedRose*'` }
end
